### ISSUE TITLE
ModuleNotFoundError: No module named 'thirdparty.nn._ext'

### ISSUE THREAD

**Issue by lululovecode** [DecaYale/RNNPose#18]
hi! I use docker to run RNNPose. But I met this error:
Traceback (most recent call last):
  File "/home/workspace/tools/eval.py", line 34, in <module>
    from utils.eval_metric import *
  File "/home/workspace/utils/eval_metric.py", line 7, in <module>
    from thirdparty.nn import nn_utils
  File "/home/workspace/thirdparty/nn/nn_utils.py", line 2, in <module>
    from thirdparty.nn._ext import lib, ffi
ModuleNotFoundError: No module named 'thirdparty.nn._ext'
I found that "_ext" thirdparty is a .c and .h file. How could I use it? Thank you very much!

**Comment by DecaYale** [comment]
Hi! Have you run the following commands? You need to compile the library before usage.
``` 
cd RNNPose/scripts
bash compile_3rdparty.sh
```
