### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by francescosarno** [DecaYale/RNNPose#20]
I have a problem while running `docker build` . I get the following error:

Dockerfile:59
--------------------
  57 |     RUN SHA=ToUcHMe git clone https://github.com/NVIDIA/apex.git
  58 |     WORKDIR /tmp/unique_for_apex/apex
  59 | >>> RUN /opt/miniconda3/envs/py37/bin/pip3 install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
  60 |     #install pytorch3d 
  61 |     # RUN /opt/miniconda3/envs/py37/bin/pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py37_cu102_pyt171/download.html
--------------------
ERROR: failed to solve: process "/bin/sh -c /opt/miniconda3/envs/py37/bin/pip3 install -v --no-cache-dir --global-option=\"--cpp_ext\" --global-option=\"--cuda_ext\" ." did not complete successfully: exit code: 1

do you know how to solve this?

**Comment by DecaYale** [comment]
Have you solved this? We tested this part, no issue had occurred. Our code can also run with the torch's distributed data parallel without apex. Maybe you just need to modify the code a little bit.

**Comment by DecaYale** [comment]
This might be caused by the update of apex repo. I suggest comment this step and try to install apex manually later. Or just use torch's distributed data parallel to replace the usage of apex. 
If you are doing an evaluation, you can also just run on a single GPU without the need for apex.    
I hope this could help.

**Comment by mqtjean** [comment]
Thank you for your answer, it seems to work fine for me commenting this command line then start my container and git clone, pip install apex. 
Indeed, apex.amp is deprecated I had to change `from apex import amp` to `from torch.cuda import amp`

**Comment by brian2lee** [comment]
> Thank you for your answer, it seems to work fine for me commenting this command line then start my container and git clone, pip install apex. Indeed, apex.amp is deprecated I had to change `from apex import amp` to `from torch.cuda import amp`

I've been facing the same problem, you've mentioned changing `from apex import amp` to `from torch.cuda import amp`, what file did you change cuz I can't find the line in the dockerfile. Sorry if this is a stupid question since I'm quite noob.

**Comment by Nishanth21D** [comment]
> Thank you for your answer, it seems to work fine for me commenting this command line then start my container and git clone, pip install apex. Indeed, apex.amp is deprecated I had to change `from apex import amp` to `from torch.cuda import amp`

hey, I did as you mentioned, but it is failing with the below error message "module 'torch.cuda.amp' has no attribute 'float_function'".

Traceback (most recent call last):
  File "/home/RNNPose/tools/eval.py", line 26, in <module>
    from builder import (
  File "/home/RNNPose/builder/rnnpose_builder.py", line 1, in <module>
    from builder import losses_builder
  File "/home/RNNPose/builder/losses_builder.py", line 2, in <module>
    from model import losses
  File "/home/RNNPose/model/losses.py", line 22, in <module>
    class Loss(nn.Module):
  File "/home/RNNPose/model/losses.py", line 65, in Loss
    @amp.float_function
AttributeError: module 'torch.cuda.amp' has no attribute 'float_function'

any workaround or can I comment it? Thanks in advance

**Comment by mqtjean** [comment]
Hello,

I'm sorry but I don't work on this project anymore and I don't have access
to this code now ..

I hope you will find the solution

Good luck in your project

Jean

Le jeu. 15 août 2024 à 12:06, Nishanth D ***@***.***> a
écrit :

**Comment by Douvahkiin** [comment]
Because the apex version is too new. This repository is released in 2022. So you must change the apex's version to 2022.

<img width="876" height="712" alt="Image" src="https://github.com/user-attachments/assets/7a2319c5-fb4a-4b6a-aa1a-144da69bf5d0" />

in Dockerfile:
```Dockerfile
# ...
WORKDIR /tmp/unique_for_apex/apex
# add this
RUN git checkout 22.03
# ...
```
Hope this will help you.
